/* This file has been generated by go-specgen */
package main


type FormatTextDB struct {
	NumBlobs uint32 
	Unknown uint32 
	TextBlobs []TextBlob  `json:"-"` 
	DataStrings *uint8  `json:"-" spec:"ptr"`  /* Buffer containing all text entry strings */
}

type TextBlob struct {
	TextID uint32  `json:"id"` 
	TextOffset uint32  `json:"-"`  /* Absolute position to a null-terminated string */
}

