/* This file has been generated by go-specgen. */
#include <stdint.h>
#include <stdio.h>

/* Format name: main */



typedef struct tagCONTROL {
	uint32_t Unknown;
	uint8_t Type[4];
	float Position[2];
	float Scale[2];
	uint32_t TextID; /* taken from Textdb_xx.def */
	uint16_t TextColor;
	uint16_t BackgroundColor;
} Control;

typedef struct tagFORMATMNU {
	uint8_t Magic[4]; /* should be 'Menu' */
	uint32_t Unknown;
	uint32_t NumControls;
	Control* Controls;
} FormatMNU;

