/* This file has been generated by go-specgen. */
#include <stdint.h>
#include <stdio.h>

/* Format name: main */



typedef struct tagTEXTBLOB {
	uint32_t TextID;
	uint32_t TextOffset; /* Absolute position to a null-terminated string */
} TextBlob;

typedef struct tagFORMATTEXTDB {
	uint32_t NumBlobs;
	uint32_t Unknown;
	TextBlob* TextBlobs;
	uint8_t* DataStrings; /* Buffer containing all text entry strings */
} FormatTextDB;

