/* This file has been generated by go-specgen. */
#include <stdint.h>
#include <stdio.h>

/* Format name: checkbin */


typedef enum {
	Pedestrian = 0x1,
	AI = 0x2,
	Vehicle = 0x4,
	Tram_Station = 0x8,
	Special = 0x10
} PointType;

typedef enum {
	Pedestrian = 1,
	AI = 2,
	Trains_Forward = 4,
	Trains_Reverse = 0x8400,
	Other = 0x1000
} LinkType;


typedef struct tagPOINT {
	PointType Type;
	uint16_t ID;
	uint16_t AreaSize;
	uint8_t Unk[10]; /* Unknown values */
	uint8_t EnterLinks; /* How many consequent links belong to this node */
	uint8_t ExitLinks; /* Is the same as EnterLinks */
} Point;

typedef struct tagLINK {
	uint16_t TargetPoint; /* Refers back to a point it connects to */
	LinkType LinkType;
	float Unk;
} Link;

typedef struct tagFORMATCHECKBIN {
	uint32_t Magic; /* Should be 0x1ABCEDF */
	uint32_t NumPoints; /* Number of navigation nodes */
	Point* Points;
	Link* Links; /* Size depends on number of links used by all points */
} FormatCheckBIN;

